name: Readme Action
on: [push]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Updates the Readme
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Action
        id: update_readme
        uses: ./
      - name: Print Result
        run: echo "Did something"