name: Readme Action
on: [push]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Updates the Readme
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch num squared
        id: get_square
        uses: ./
      - name: Print Result
        run: echo "Did something"